Create Teamcity build chain
octopusden/octopus-teamcity-automation pull request #15
Opened 2024-09-05 15:30 UTC by qu0d

2024-09-05 15:41 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        log.debug("VCS = {}", componentsRegistryClient.getVCSSetting(componentName, minorVersion))
Очень странное местоположение для такого логирования. Почему не в методе createVcsRoot?

2024-09-05 15:45 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        val counter = object {
Зачем такие сложности, если counter может быть просто Int, а вместо getCounterIncMajor можно написать "${counter++}.0" ?

2024-09-05 15:47 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +                RepositoryType.MERCURIAL -> client.createVcsRoot(
Я не уверен что нам надо поддерживать это. Вариант миграции с git на mercurial видится мне ничтожно маловероятным.

2024-09-05 15:53 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        return when (buildSystem) {
Мне кажется вся возня с Template классами какая-то бессмысленная. Достаточно в companion object прописать 5 строковых констант и добавить метод getCompileUtTemplate, который бы возвращал if (buildSystem = MAVEN) MAVEN_TEMPLATE else GRADLE_TEMPLATE.

Я не представляю, чтобы эти классы потом потребовалось где-то переиспользовать.

2024-09-05 15:55 UTC, CamaradeRoman requested changes

2024-09-05 15:55 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +    private fun attachVcsLabelingFeature(buildTypeId: String, vcsRootId: String?) {
Мы же ушли от использования этой фичи и стоит задача у тебя же - удалить её с текущих билд чейнов.

2024-09-05 15:59 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +                        TeamcityProperty("run-build-on-the-same-agent", "false"),
Возможно стоит завести какой-нибудь object с константами имен стандартных пропертей и их возможных значений. Может даже в самом TeamCityClient.

2024-09-06 07:04 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +    private val componentsRegistryClient by lazy {
не только в run

2024-09-06 07:14 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        log.debug("VCS = {}", componentsRegistryClient.getVCSSetting(componentName, minorVersion))
Удалил. Мусор

2024-09-06 07:22 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        val counter = object {
Наследство от Саши

2024-09-06 07:24 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +                RepositoryType.MERCURIAL -> client.createVcsRoot(
Удалил

2024-09-06 07:40 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        return when (buildSystem) {
Дело вкуса. Оставил бы как у Саши. По моему, это не улучшит код.
Иногда классы нужны, чтобы  смысл обозначить.

2024-09-06 08:37 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +    private fun attachVcsLabelingFeature(buildTypeId: String, vcsRootId: String?) {
Удалил

2024-09-06 09:11 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +                        TeamcityProperty("run-build-on-the-same-agent", "false"),
Сложно найти найти сами костанты, но согласен, что если есть часто используемые надо выносить в клиента.

2024-09-06 10:20 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        val counter = object {
Переделал

2024-09-06 10:20 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        return when (buildSystem) {
Упростил

2024-09-06 10:25 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +    private val componentsRegistryClient by lazy {
а где еще?

не надо пожалуйста закрывать conversation, лучше оставить это тому, кто написал замечание (ну кроме суперочевидных случаев, когда просят опечатку поправить например)

2024-09-06 10:34 UTC, qu0d commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +    private val componentsRegistryClient by lazy {
Не прав, почему-то решил, что вопрос про TeamCityClient.
componentsRegistryClient только в run.
Перенесу в run

2024-09-06 10:42 UTC, CamaradeRoman commented on src/main/kotlin/org/octopusden/octopus/automation/teamcity/TeamcityCreateBuildChainCommand.kt
> +        var counter: Int = 0
IDEA должна тут рисовать Explicitly given type is redundant. Но это мелочи и исправлять не надо.

2024-09-06 10:43 UTC, CamaradeRoman approved these changes

2024-09-06 11:55 UTC, fishinitself approved these changes

2024-09-06 12:58 UTC, merged